build: reference to custom internal private fonts (fakes), update doc and hook (#89)
Related to Orange-OpenSource/ouds-ios#1006

We need to have reference to files with particular names (here Helvetica Neue LT Arabic TTF files) so as to compile the project. If the files are missing but defined in pbxproj / Xcode target, the project won't compile.
But we cannot version such files because of restrictions in terms of uses.
So, this commit bring an exotic solution:
- version fake files, with same name and extension, but empty
- explain why in README of the dedicated folder
- keep references in targets
- update pre-commit hook to prevent modifications of these files (e.g. if bad manipulation and original commited)

Thus the project will compile and in our internal forge a simple copy/paste of the touchy assets will be enough because already assigned.

In this repo, a default font fmaily will be applied if TTF are missing.

Assisted-by: GPT-4.1-nano (Dinootoo)
Acked-by: Ludovic Pinel <ludovic.pinel@orange.com>
Signed-off-by: Pierre-Yves Lapersonne <pierreyves.lapersonne@orange.com>

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -13,7 +13,8 @@
 #
 
 # pre-commit hook to format Swift sources before submitting them to remote
-# Ensures source code is always formatted.
+# Checks also if some files have been modified and stagde even if they are supposed to be excluded.
+# Ensures source code is always formatted without leak of touchy files.
 
 # Configuration
 # -------------
@@ -22,12 +23,30 @@ export PATH="$PATH:/opt/homebrew/bin"
 
 formatterExec=$(which swiftformat)
 
+# List of files for which, supposing they exist and are empty, must not have changes 
+# (supposing in that case the original version and not empty are commited which is not acceptable)
+# See Orange-OpenSource/ouds-ios#1066
+exclusion_list=("HelveticaNeueLTArabic-Bold.ttf" "HelveticaNeueLTArabic-Light.ttf" "HelveticaNeueLTArabic-Roman.ttf")
+
 # Functions
 # ---------
 
+checkExclusions() {
+  staged_files=$(git diff --diff-filter=d --staged --name-only)
+  for staged_file in $staged_files; do
+    filename=$(basename "$staged_file")
+    for excluded in "${exclusion_list[@]}"; do
+      if [ "$filename" = "$excluded" ]; then
+        echo "💥 ERROR: The file '$filename' is in exclusion list and must not be modified."
+        exit 1
+      fi
+    done
+  done
+}
+
 checkIfSwiftFormatInstalled() {
   if [ ! -x "$formatterExec" ]; then
-    1>&2 echo "💥 Unable to find swiftformat - no formatting will take place"
+    1>&2 echo "💥 ERROR: Unable to find swiftformat - no formatting will take place"
     exit 0
   fi
 }
@@ -54,6 +73,8 @@ formatStagedFiles() {
 # Main
 # ----
 
+echo "🧹 Checking of some trials of modification of excluded files"
+checkExclusions
 echo "🧹 Cleaning sources before commit..."
 checkIfSwiftFormatInstalled
 formatStagedFiles
